### ISSUE TITLE
Request for a release

### ISSUE THREAD

**Issue by mbarbin** [ocaml-dune/pp#20]
Hello,
I would like to request the submission of a release for the pp project to the opam repository. I'd like to use the couple new helpers that were added, plus it's been a little while since the last release.
Thanks!

**Comment by rgrinberg** [comment]
Do you want to do the honours? I added you as a maintainer.

**Comment by mbarbin** [comment]
Yes! Thank you for appointing me as a maintainer.

Looking back at the unreleased changes, I see #17 which is a breaking change. Does it warrant a major semver increase? In theory I would say yes (a.k.a. releasing pp.2.0.0). That being said I looked via sherlocode, and didn't find a match for the `Pp.of_fmt`, outside of the test for this library. https://sherlocode.com/?q=Pp.of_fmt

For commits that prepare the changelog, do maintainers push directly to the main branch, or is it better to go via a PR as well?

**Comment by rgrinberg** [comment]
> Looking back at the unreleased changes, I see https://github.com/ocaml-dune/pp/pull/17 which is a breaking change. Does it warrant a major semver increase? In theory I would say yes (a.k.a. releasing pp.2.0.0). That being said I looked via sherlocode, and didn't find a match for the Pp.of_fmt, outside of the test for this library. [sherlocode.com?q=Pp.of_fmt](https://sherlocode.com/?q=Pp.of_fmt)

Both are acceptable to me. `Pp.of_fmt` was not very useful in hindsight as it breaks the purpose of this library which is serialization.

> For commits that prepare the changelog, do maintainers push directly to the main branch, or is it better to go via a PR as well?

Whatever you prefer.

**Comment by mbarbin** [comment]
> Pp.of_fmt was not very useful in hindsight as it breaks the purpose of this library which is serialization.

So far I've used `pp` in a spirit that matches what the introductory paragraph says in the home page's README, and didn't think about serialization. I'm curious - does Dune use `Pp` to send errors to `ocaml-lsp`? Are there other use cases? 

I'm inclined to name the release `2.0.0`. The focus on serialization could be considered a minor change to the original project motivation, hereby dropping the (unused says sherlocode) `Pp.of_fmt` feature of "making it easier to migrate code from using Format to using Pp". That sounds fine to me.

I'm going to be on and off the next few days, so I might not get to it right away, but please consider it on my stack and I will get this release done. Thanks!

**Comment by rgrinberg** [comment]
> I'm curious - does Dune use Pp to send errors to ocaml-lsp? Are there other use cases?

Yes, it was introduced exactly for this purpose. No other use cases as far so far as I'm aware. We also introduced a combinator based API because of the general dislike for format strings.

> I'm inclined to name the release 2.0.0. The focus on serialization could be considered a minor change to the original project motivation, hereby dropping the (unused says sherlocode) Pp.of_fmt feature of "making it easier to migrate code from using Format to using Pp". That sounds fine to me.

That's OK.

> I'm going to be on and off the next few days, so I might not get to it right away, but please consider it on my stack and I will get this release done. Thanks!

Roger.

**Comment by mbarbin** [comment]
Work in progress in #21.

**Comment by mbarbin** [comment]
Merged https://github.com/ocaml/opam-repository/pull/26570
